const lessons = [
	{
		name: 'John Smith',
		topic: 'Semantic html tags',
		description: 'In this lesson I will show you simple, semantic html & its benefits',
		zoom: 'http://zoom.com',
		paypalemail: 'test@example.com',
		datetime: '2022-06-25T17:30',
		duration: 30,
		starrating: 5,
	},
    {
        name: 'John Wayne',
        topic: 'VS code shortcuts you need to know',
        description: 'Learn how to use VS code shortcuts to speed up your coding!',
        zoom: 'http://zoom.com',
        paypalemail: 'britney@example.com',
        datetime: '2022-06-20T15:00',
        duration: 30,
        starrating: 5,
    },
	{
		name: 'Laura Jones',
		topic: 'All you need to know about JS',
		description: 'Just 30 minutes and I will shape your mind to understand the principles of JS!',
		zoom: 'http://zoom.com',
		paypalemail: 'test2@example.com',
		datetime: '2022-07-30T19:30',
		duration: 30,
		starrating: 5,
	},
	{
		name: 'Randy White',
		topic: 'Python basics in 3 easy steps',
		description: '60 minutes to launch your personal development & automate the boring stuff!',
		zoom: 'http://zoom.com',
		paypalemail: 'test3@example.com',
		datetime: '2022-06-29T18:00',
		duration: 30,
		starrating: 3,
	},
	{
		name: 'Mike Tyson',
		topic: "Everyone's got a SQL Query Until they don't",
		description: "How to make sense of a SQL query. I'll show you how to do it!",
		zoom: 'http://zoom.com',
		paypalemail: 'mike@example.com',
		datetime: '2022-07-25T11:30',
		duration: 45,
		starrating: 5,
	},
	{
		name: 'Jordan Boney',
		topic: "5 things you need to know about React props",
		description: "Learn how to use React props to pass data to your components!",
		zoom: 'http://zoom.com',
		paypalemail: 'mike@example.com',
		datetime: '2022-07-25T11:30',
		duration: 45,
		starrating: 5,
	},
]

export default lessons;